services:
  scanner:
    build:
      context: .
      dockerfile: ./docker/discovery.Dockerfile
    container_name: scanner
    command: python scanner.py
    restart: on-failure
    cap_add:
      - NET_RAW
      - NET_ADMIN
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
