version: '3.8'

services:
  api:
    build:
      context: api_applications
      dockerfile: docker/Dockerfile
    volumes:
      - api_applications:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - broker
    restart: always

  broker:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  db:
    container_name: postgres
    image: postgres:17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:      
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}



  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: always
    env_file:
      - .env
    networks:
      - mynetwork


  scanner:
    build:
      context: .
      dockerfile: ./docker/discovery.Dockerfile
    container_name: scanner
    command: python scanner.py
    restart: on-failure
    networks:
      - mynetwork
    env_file:
      - .env
    cap_add:
      - NET_RAW
      - NET_ADMIN
    depends_on:
      - mongodb

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: