version: '3.8'

services:
  api:
    build:
      context: ../api_applications
      dockerfile: docker/Dockerfile
    volumes:
      - ../api_applications:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - broker
    restart: always

  broker:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  db:
    container_name: postgres
    image: postgres:17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:      
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}

volumes:
  postgres_data:
