# Generated by Django 5.2 on 2025-07-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_models', '0003_subscriptionplan_userprofile_membership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf',
        ),
        migrations.AddField(
            model_name='invoice',
            name='metadata',
            field=models.JSONField(default=[{}]),
            preserve_default=False,
        ),
    ]
